### ISSUE TITLE
Say hi！

### ISSUE THREAD

**Issue by zyascend** [OceanPresentChao/OceanPresent.art#1]
hello， 我也是吉大软院的研究生，好兄弟研几的？

**Comment by OceanPresentChao** [comment]
软院大二QWQ

**Comment by zyascend** [comment]
> 软院大二QWQ

哈哈 强强强😀 看你的个人网站还以为是研究生呢

**Comment by OceanPresentChao** [comment]
加个qq一起学习交流吧。QQ:1255342403

**Comment by OceanPresentChao** [comment]
> > 软院大二QWQ
> 
> 哈哈 强强强😀 看你的个人网站还以为是研究生呢

可以加我的qq 1255342403，有机会多交流=v=
